### PR TITLE
various changes for concept alignment

### PR DESCRIPTION
**Pull request by harisont**
Here is a summary of the changes:

- deleted `AlignTrees` (well, moved it to the `concept-alignment` repository)
- modified `BuildGFGrammar` (to use it in `concept-alignment`'s `GenerateGrammar`, these two should probably become a single program which could belong to either repository)
- moved `RTree` functions not specific to GF or UD trees from `GFConcepts` to a new module called `RTree`
- added some more functions to `RTree`
- fixed a minor bug related to paths with multiple `/` (already opened a pull request specifically for that)
- added some UD trees-specific functions to `UDConcepts` (e.g. for comparing trees taking only some features into account)
- in `UDConcepts`, simplified `prUDSentence` so that `sent_ids` are just numbers starting from 1 (but it looks like there are good reasons to revert this?)
- added out folder, stack stuff, `.gfo`  and `.pgf` files to gitignore

### CODE REVIEW

**Comment by aarneranta** [comment]
Thanks! If gfud still compiles with these changes, they should be OK. The new RTree module needs to be imported in several places I guess.


  Aarne

________________________________

**Comment by harisont** [comment]
Yes, it does compile and RTree is imported in the various other modules now.
The only thing that you should really check before merging is

> in UDConcepts, simplified prUDSentence so that sent_ids are just numbers starting from 1 (but it looks like there are good reasons to revert this?)

The numbering was different because of some requirements of the malt parser, but it was a bit peculiar, I wonder if it is still necessary to keep it that way...?

**Comment by harisont** [comment]
For every input, because the original numbering started from 1000001 and each id was preceded by "gfud", so 
gfud1000001,gfud1000002 
and so on. The new one is instead
1,2...

But obviously I can switch back

**Comment by aarneranta** [comment]
I prefer the old numbering, because it is easier to sort by Unix tools. And also change globally, e.g. gfud1 -> gfud2 if we want to combine two treebanks.


  Aarne.

________________________________

**Comment by harisont** [comment]
Now it is again as it was initially, I'm not sure about the other change you were mentioning

**Comment by aarneranta** [comment]
Numbering the sentences was the only change I needed. Everything is merged now. Thanks for your contributions!


  Aarne.

________________________________

**Pull request merged**
